### ISSUE TITLE
Code release for robotic demonstration

### ISSUE THREAD

**Issue by mrcyme** [WinKawaks/SketchDreamer#1]
Hello,

Thanks for the great work ! It happens to be exactly what I am looking for. 
Indeed, I would like to create an installation where a visitor give a text prompt and draw something on a board and then, a robotic arm complete the drawing.
Have you planned on releasing the code ? I would be verry happy if you do so (even an undocumented, uncleaned version)  !
Of course I would credit you and the other authors. 

Cheers

**Comment by WinKawaks** [comment]
@mrcyme Hi! Thank you for your interest in my work. Sorry that I don't plan to release the code in a few months because I still have some similar ideas based on it. Meanwhile, I am very interested in Robotics. Do you mind if we have a brief communication via email? I'm looking for some cooperation. My email is z.qu@surrey.ac.uk
